CRUD-CORE-MVC/CRUD-CORE-MVC/Models/ContactoModel.cs
using System.ComponentModel.DataAnnotations;

namespace CRUD_CORE_MVC.Models
{
    public class ContactoModel
    {
        public int idContacto { get; set; }
        [Required (ErrorMessage ="El campo Nombre es obligatorio")]
        public string? Nombre { get; set; }
        [Required]
        public string? Telefono { get; set; }
        [Required]
        public string? Email { get; set; }
    }
}

CRUD-CORE-MVC/CRUD-CORE-MVC/Models/ErrorViewModel.cs
namespace CRUD_CORE_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD-CORE-MVC/CRUD-CORE-MVC/Controllers/HomeController.cs
using CRUD_CORE_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUD_CORE_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD-CORE-MVC/CRUD-CORE-MVC/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using CRUD_CORE_MVC.Datos;
using CRUD_CORE_MVC.Models;

namespace CRUD_CORE_MVC.Controllers
{
    public class MantenedorController : Controller
    {
        ContactoDatos _ContactoDatos = new ContactoDatos();
        public IActionResult Listar()
        {
            //Mostrar lista de contactos
            var oLista = _ContactoDatos.Listar();
            return View(oLista);
        }
        public IActionResult Guardar()
        {
            //Mostrar formulario
            return View();
        }
        [HttpPost]
        public IActionResult Guardar(ContactoModel oContacto)
        {
            //Accion Guardar
            if (!ModelState.IsValid)
                return View();
            var rta = _ContactoDatos.Guardar(oContacto);
            if (rta)
                return RedirectToAction("Listar");
            else
                return View();
        }
        public IActionResult Editar(int idContacto)
        {
            //Mostrar formulario editar
            var oContacto = _ContactoDatos.Obtener(idContacto);
            return View(oContacto);
        }
        [HttpPost]
        public IActionResult Editar(ContactoModel oContacto)
        {
            //Accion Editar-Guardar
            if (!ModelState.IsValid)
                return View();
            var rta = _ContactoDatos.Editar(oContacto);
            if (rta)
                return RedirectToAction("Listar");
            else
                return View();
        }
        public IActionResult Eliminar(int idContacto)
        {
            //Mostrar formulario editar
            var oContacto = _ContactoDatos.Obtener(idContacto);
            return PartialView("_EliminarContactoPartial",oContacto);
        }
        [HttpPost]
        public IActionResult Eliminar(ContactoModel oContacto)
        {
            //Accion Editar-Guardar
            var rta = _ContactoDatos.Eliminar(oContacto.idContacto);
            if (rta)
                return RedirectToAction("Listar");
            else
                return PartialView("_EliminarContactoPartial");
        }
    }
}

CRUD-CORE-MVC/CRUD-CORE-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD-CORE-MVC/CRUD-CORE-MVC/Views/Mantenedor/Editar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar Contacto
    </div>
    <div class="card-body">
        <form asp-action="Editar" asp-controller="Mantenedor" method="post">
            <input asp-for="idContacto" type="hidden" class="form-control">
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Telefono</label>
                <input asp-for="Telefono" type="text" class="form-control">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">E-mail</label>
                <input asp-for="Email" type="text" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">GUARDAR</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
</div>

CRUD-CORE-MVC/CRUD-CORE-MVC/Views/Mantenedor/Eliminar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<div class="card">
    <div class="card-header">
        Eliminar Contacto
    </div>
    <div class="card-body">
        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">
            <input asp-for="idContacto" type="hidden" class="form-control">
            <div class="alert alert-danger" role="alert">
                Esta a punto de eliminar al contacto: @Html.DisplayTextFor(m=>m.Nombre)
            </div>
            <button type="submit" class="btn btn-danger">ELIMINAR</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-secondary">ver LISTA</a>
        </form>
    </div>
</div>*@

<!-- Modal -->
<div class="modal fade" id="e" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

CRUD-CORE-MVC/CRUD-CORE-MVC/Views/Mantenedor/Guardar.cshtml
@model  ContactoModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card">
    <div class="card-header">
        Crear Contacto
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Telefono</label>
                <input asp-for="Telefono" type="text" class="form-control">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">E-mail</label>
                <input asp-for="Email" type="text" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">GUARDAR</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
</div>

CRUD-CORE-MVC/CRUD-CORE-MVC/Views/Mantenedor/Listar.cshtml
@model List<ContactoModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <b>LISTA DE CONTACTOS</b>
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success"><i class="bi bi-plus-circle"></i> NUEVO CONTACTO</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Email</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td>@item.Email</td>
                        <td>
                            @*<a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm" asp-route-idContacto="@item.idContacto"><i class="bi bi-trash"></i></a>*@

                            <!-- Button trigger modal -->
                            <a class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="@("#EliminarContact-"+item.idContacto)" >
                                <i class="bi bi-trash"></i> ELIMINAR
                            </a>
                            @await Html.PartialAsync("~/Views/PartialViews/_EliminarContactoPartial.cshtml",item)
                            @*data-url="@Url.Action($"Eliminar/{item.idContacto}")"*@
                            <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" asp-route-idContacto="@item.idContacto"><i class="bi bi-pencil-square"></i> EDITAR</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


@*<!-- Modal -->
<div class="modal fade" id="e" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>*@

CRUD-CORE-MVC/CRUD-CORE-MVC/Views/PartialViews/_EliminarContactoPartial.cshtml
@model ContactoModel
<!-- Modal -->
<div class="modal fade" id="EliminarContact-@Model.idContacto" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">ELIMINAR CONTACTO</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="Eliminar" method="post">
                    <input asp-for="idContacto" type="hidden" class="form-control">
                    <div class="alert alert-danger" role="alert">
                        Esta a punto de eliminar a: @Html.DisplayTextFor(m=>m.Nombre)
                    </div>
                    <button type="submit" class="btn btn-danger">ELIMINAR</button>
                    <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-secondary">Cancelar</a>
                </form>
            </div>
            @*<div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>*@
        </div>
    </div>
</div>

CRUD-CORE-MVC/CRUD-CORE-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_CORE_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_CORE_MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica CRUD con MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mantenedor" asp-action="Listar">Contactos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRUD_CORE_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>